import Foundation
import ImageIO
import CoreGraphics

@main
struct AnimatedImageFixtures {
    static func main() {
        // Real two-frame GIF bytes, generated by ImageIO, intentionally no filename.
        let data = NSMutableData()
        let destination = CGImageDestinationCreateWithData(data, "com.compuserve.gif" as CFString, 2, nil)!
        for channel in [UInt8(0), UInt8(255)] {
            let bytes = Data([channel, 0, 255, 255])
            let provider = CGDataProvider(data: bytes as CFData)!
            let image = CGImage(width: 1, height: 1, bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: 4, space: CGColorSpaceCreateDeviceRGB(), bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.last.rawValue), provider: provider, decode: nil, shouldInterpolate: false, intent: .defaultIntent)!
            CGImageDestinationAddImage(destination, image, [kCGImagePropertyGIFDictionary: [kCGImagePropertyGIFDelayTime: 0.1]] as CFDictionary)
        }
        precondition(CGImageDestinationFinalize(destination))
        let source = CGImageSourceCreateWithData(data, nil)!
        precondition(CGImageSourceGetType(source) as String? == "com.compuserve.gif")
        precondition(CGImageSourceGetCount(source) == 2)
        for index in 0..<2 {
            precondition(CGImageSourceCreateThumbnailAtIndex(source, index, [kCGImageSourceCreateThumbnailFromImageAlways: true, kCGImageSourceThumbnailMaxPixelSize: 64] as CFDictionary) != nil)
        }
        print("PASS real generated GIF signature, two frames and bounded ImageIO decode (synthetic fixture, not live-site acceptance)")
    }
}
